#!/bin/bash

# Copyright (c) 2017 Ryoto Saito
#
# This software is released under the MIT License.
# http://opensource.org/licenses/mit-license.php

set -Ceu
tty=$(tty)
i=1;
####################################
##### Main #########################
####################################
(
	while :
	do
		echo -ne "\033[G\033[1M"
		echo -ne "\033[30;47m${@:i:1}\033[m"
		read -rsn1 key
		if [[ "$key" == $'\x1b' ]]; then
			read -rsn2 rest
			key="$key$rest"
		fi
		case "$key" in
			$'\x1b\x5b\x41' ) # up key
				if [[ $i -gt 1 ]]; then
					i=$(echo $i - 1 | bc)
				fi;;
			$'\x1b\x5b\x42' ) # down key
				if [[ $i -lt $(expr $#) ]]; then
					i=$(echo $i + 1 | bc)
				fi;;
			"" ) # enter key
				echo
				break;;
		esac
	done
	echo -ne "\033[F\033[1M"
	echo "${@:i:1}"
)>$tty
echo "${@:i:1}" #return
