#!/bin/bash

# Copyright (c) 2017 Ryoto Saito
#
# This software is released under the MIT License.
# http://opensource.org/licenses/mit-license.php

function help() {
	(
		echo "Options:"
		echo "  -k^output key instead of value"
		echo "  -p prompt^set prompt before options"
		echo "  -q^don't echo selected value"
	) | column -t -s ^
	exit;
}

set -Ceu
tty=$(tty)
i=1;

####################################
##### Get Option ###################
####################################
while getopts hkp:q OPT
do
	case $OPT in
		h)  help
			;;
		k)	FLAG_K=1
			;;
		p)  FLAG_P=1
			VALUE_P=$OPTARG
			;;
		q)  FLAG_Q=1
			;;
	esac
done
shift $((OPTIND - 1))

####################################
##### Main #########################
####################################
{
	while :
	do
		echo -ne "\033[G\033[1M"
		if [[ ${FLAG_P-} ]]; then
			echo -ne "${VALUE_P-}"
		fi
		echo -ne "\033[30;47m${@:i:1}\033[m"
		read -rsn1 key
		if [[ "$key" == $'\x1b' ]]; then
			read -rsn2 rest
			key="$key$rest"
		fi
		case "$key" in
			$'\x1b\x5b\x41' ) # up key
				if [[ $i -gt 1 ]]; then
					i=$((i-1))
				fi;;
			$'\x1b\x5b\x42' ) # down key
				if [[ $i -lt $(($#)) ]]; then
					i=$((i+1))
				fi;;
			"" ) # enter key
				echo
				break;;
		esac
	done
	echo -ne "\033[F\033[1M"
	if [[ ! ${FLAG_Q-} ]]; then
		if [[ ${FLAG_P-} ]]; then
			echo -ne "${VALUE_P-}"
		fi
		echo "${@:i:1}"
	fi
}>"$tty"
####################################
##### Return #######################
####################################
if [[ ${FLAG_K-} ]]; then
	echo $((i-1))
else
	echo "${@:i:1}"
fi
